image: markhobson/maven-chrome:jdk-11

stages:
  - build
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn clean test

after_script:
  - cd Ivoice
  - mvn allure:report
artifacts:
  when: always
  name: "Report"
  paths: "-$CI_PROJECT_DIR/Ivoice/target/site/allure-maven-plugin/"
  expire_in: 15 days



